name: surfWave
channels:
  - defaults
  - conda-forge
  - mila-udem
dependencies:
  - ffmpeg>=4.1.3
  - matplotlib-base>=3.1.0
  - opencv>=4.1.0
  - qt>=5.9.7
  - sk-video>=1.1.10
  - h5py>=2.9.0
  - hdf5>=1.10.4
  - jupyter
  - mkl>=2018.0.3
  - nbconvert>=5.5.0
  - numpy>=1.16.4
  - numpy-base>=1.16.4
  - pyqt>=5.9.2
  - python>=3.6.8
  - scikit-image>=0.16.2
  - scipy=1.3.0
  - pandas
  - psutil>=5.7.0
